force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <label>Realtor Agency</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <label>Commission Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Date_Sold__c.field-meta.xml
<CustomField>
    <fullName>Date_Sold__c</fullName>
    <label>Date Sold</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Realtor__c.field-meta.xml
<CustomField>
    <fullName>Realtor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Realtor</label>
    <referenceTo>Realtor__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Realtor__c/Realtor__c.object-meta.xml
<CustomObject>
    <label>Realtor</label>
    <nameField>
        <label>Realtor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Realtors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CommissionController.cls
public class CommissionController {
	@AuraEnabled
    public static List<Commission__c> getCommissions() {
        return [SELECT id, Realtor__r.Name, Commission_Amount__c, Name, Date_Sold__c, Paid__c, CreatedDate 
                FROM Commission__c
               ORDER BY CreatedDate];
	}
    
    @AuraEnabled
    public static Commission__c saveCommission(Commission__c commission) {
        upsert commission;
        return commission;
    }
}