force-app/main/default/objects/Customer__c/fields/Buy_Date__c.field-meta.xml
<CustomField>
    <fullName>Buy_Date__c</fullName>
    <label>Buy Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Homeowner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lot__c/Lot__c.object-meta.xml
<CustomObject>
    <label>Lot</label>
    <nameField>
        <label>Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lot__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Lots</relationshipLabel>
    <relationshipName>Lots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lot__c/fields/Neighborhood__c.field-meta.xml
<CustomField>
    <fullName>Neighborhood__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Neighborhood</label>
    <referenceTo>Neighborhood__c</referenceTo>
    <relationshipLabel>Lots</relationshipLabel>
    <relationshipName>Lots</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Developed</fullName>
            </value>
            <value>
                <fullName>Acquiring Permits</fullName>
            </value>
            <value>
                <fullName>Awaiting Permission</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Construction Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Neighborhood__c/Neighborhood__c.object-meta.xml
<CustomObject>
    <label>Neighborhood</label>
    <nameField>
        <label>Neighborhood Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Neighborhoods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Neighborhood__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Building Soon</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestBuyerSearch_AC.cls
@isTest
private class TestBuyerSearch_AC {
    @isTest
    private static void TestBuyerSearch_AC() {
         
        Date FixedDate = Date.Today() - 5;
  
        Customer__c TestCustomer = new Customer__c();
        TestCustomer.Name= 'Test Name';
        TestCustomer.Status__c='Buyer';
        TestCustomer.Buy_Date__c= FixedDate;
        insert TestCustomer;

        Neighborhood__c TestNeigh = new Neighborhood__c();
        TestNeigh.Name = 'Test Neigh';
        TestNeigh.Status__c = 'In Development';
        insert TestNeigh;

        Lot__c TestLot = new Lot__c();
        TestLot.Name = 'Test Lot';
        TestLot.Neighborhood__c = TestNeigh.Id;
        TestLot.Status__c = 'Developed';
        TestLot.Customer__c = TestCustomer.Id;
        insert TestLot;

        test.startTest();
        
        Date TestDate = Date.today() - 6;
        List<Lot__c> TestLotList = new List<Lot__c>([SELECT Neighborhood__r.Name, Name, Status__c, Customer__r.Name, Customer__r.Status__c, Customer__r.Buy_Date__c 
                                                FROM Lot__c 
                                                WHERE Customer__r.Status__c = 'BUYER' AND Customer__r.Buy_Date__c > :TestDate 
                                                ORDER BY Customer__r.Buy_Date__c DESC]);
        for(Lot__c L : TestLotList){
            system.assertEquals(FixedDate, L.Customer__r.Buy_Date__c);
        }       
         
                                    
        test.stopTest();
        BuyerSearch_AC.BuyerSearchWithDate(5);
        
    }
}