force-app/main/default/objects/Customer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Homeowner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerRealtorListTest.cls
@isTest
private class CustomerRealtorListTest {
    @TestSetup
    static void makeData() {
         List<Customer__c> customers = new List<Customer__c>();
         for (Integer i = 0; i < 200; i++) {
             customers.add(new Customer__c());
             customers[i].Name = 'Jane Doe ' + i;
             customers[i].Status__c = 'Lead';
         }
         
         insert customers;
    }

    @isTest
    static void customer() {
        List<Customer__c> customers = CustomerRealtorListController.retrieveCustomers();
        System.assertEquals(200, customers.size());
    }
}