force-app/main/default/objects/Lot__c/Lot__c.object-meta.xml
<CustomObject>
    <label>Lot</label>
    <nameField>
        <label>Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lot__c/fields/Neighborhood__c.field-meta.xml
<CustomField>
    <fullName>Neighborhood__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Neighborhood</label>
    <referenceTo>Neighborhood__c</referenceTo>
    <relationshipLabel>Lots</relationshipLabel>
    <relationshipName>Lots</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Neighborhood__c/Neighborhood__c.object-meta.xml
<CustomObject>
    <label>Neighborhood</label>
    <nameField>
        <label>Neighborhood Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Neighborhoods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DisplayHousePicCC.cls
public class DisplayHousePicCC {
    
    @AuraEnabled
    public static List<Neighborhood__c> getNeighborhood(){
        List<Neighborhood__c> proplist = [Select Id, Name FROM Neighborhood__c];
        return proplist;   
    }  
   @AuraEnabled
    public static List<Lot__c> getLots(String propId){
     List<Lot__c> unitList =[Select Id, Name,Neighborhood__c FROM Lot__c where Neighborhood__c =: propId];
        return unitList;
    }
    @AuraEnabled
    public static List<ContentVersion> getContents(string brandId, string ObjectName) {
        Set<Id> contentIds = new Set<Id>();
        if(ObjectName == 'Neighborhood__c'){
            for (ContentDocumentLink cont :[SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink where LinkedEntityId in ( SELECT Id FROM Neighborhood__c where Id =: brandId) and LinkedEntity.Type=:ObjectName]) 
            {contentIds.add(cont.ContentDocumentId);
            }
        }else{
            for (ContentDocumentLink cont :[SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink where LinkedEntityId in ( SELECT Id FROM Lot__c where Id =: brandId) and LinkedEntity.Type=:ObjectName])
            {contentIds.add(cont.ContentDocumentId);   
            }
        }
return [SELECT Id,Title FROM ContentVersion WHERE ContentDocumentId IN :contentIds LIMIT 1];
    }
}