force-app/main/default/objects/Lot__c/Lot__c.object-meta.xml
<CustomObject>
    <label>Lot</label>
    <nameField>
        <label>Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lot__c/fields/Neighborhood__c.field-meta.xml
<CustomField>
    <fullName>Neighborhood__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Neighborhood</label>
    <referenceTo>Neighborhood__c</referenceTo>
    <relationshipLabel>Lots</relationshipLabel>
    <relationshipName>Lots</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Developed</fullName>
            </value>
            <value>
                <fullName>Acquiring Permits</fullName>
            </value>
            <value>
                <fullName>Awaiting Permission</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Construction Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Neighborhood__c/Neighborhood__c.object-meta.xml
<CustomObject>
    <label>Neighborhood</label>
    <nameField>
        <label>Neighborhood Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Neighborhoods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Neighborhood__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Building Soon</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LotPaginationControllerTest.cls
@isTest
public with sharing class LotPaginationControllerTest {
    private static List<Lot__c> testLots;
    //number of test lots to create
    private static Integer numOfLots = 6;
    
    @TestSetup
    static void makeLots(){
        testLots = new List<Lot__c>();
        Id neighborhoodDefault = 'a025f000000VbZsAAK';
        List<String> statuses = new List<String> {'Developed', 'Construction Complete', 'Under Construction'};
        for(Integer i = 0; i < numOfLots; i++){
            Lot__c lotToTest = new Lot__c(Name='Test '+i, Neighborhood__c=neighborhoodDefault, Status__c=statuses.get(Math.Mod(i, 2)));
            testLots.add(lotToTest);
        }
    }
    
     @isTest
     static void testLotShows(){
         // stick in test data
         makeLots();
        
         
         //Begin Test
         Test.startTest();
         insert testLots;
         List<Lot__c> lots = lotPaginationController.grabLots();
        
        //test whether or not lots is non null and has size > 0
        System.debug('lots: ' + lots[0].Name );
        System.assert(lots != null && lots.size() > 0);
        Test.stopTest();
     }
    
    @isTest
     static void testLotQuery(){
         // stick in test data
         makeLots();
        
         
         //Begin Test
         Test.startTest();
         insert testLots;
         List<Lot__c> lots = FilterLotListController.allLots('1');
        
        //test whether or not lots is non null and has size = 1
        System.debug('lots: ' + lots[0].Name );
        System.assert(lots != null && lots.size() > 0);
        Test.stopTest();
     }
}